### ISSUE TITLE
startWriting() method not working properly 

### ISSUE THREAD

**Issue by mariedm** [svtek/SceneKitVideoRecorder#14]
I can't make the new version work. I'm probably doing something wrong.

Like the demo project, I'm calling:
- `recorder=try! SceneKitVideoRecorder(withARSCNView: sceneView)` in `viewDidLoad()`
- `recorder.setupMicrophone()` in `viewWillAppear`
- then `recorder.startWriting()` when pushing the record button 

`startDisplayLink()` method is never called. So when `finishWriting` is called, `isRecording` is false and it returns without actually stoping the recording.
Then when I push the record button again I get `Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriter addInput:] Cannot call method when status is 3'`.

**Comment by okaris** [comment]
I just pushed some new changes. 

Please make sure that:
- You can reproduce this with the Demo Project
- You can reproduce this with a clean install
- You are running on a Device and not the Simulator

**Comment by mariedm** [comment]
I'm running 1.3.1 version on an actual device (iPhone 7). What do you mean by clean install? 

I didn't manage to run the Demo Project, I have a pod issue: `diff: /Podfile.lock: No such file or directory` and `The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation`. I ran `pod install` and `pod update` but it did not solve the issue. 

I know it's not exactly the same but I recreated the demo project myself with 1.3.1 pod version. 

Sorry for the lack of help I'm providing you.

**Comment by okaris** [comment]
No problem at all.

For a clean install please remove the demo app from your device. I have just pushed the updated lock file. Can you try running the demo project again please. 

The demo project runs the latest code that is adjacent. Some changes might not be reflected in the latest pod version. That might be the issue here.

If you are still not able to run the demo project. Please try in your own project by copying the source files instead of using the Pod to test.

**Comment by mariedm** [comment]
I'm not sure that's what you asked me but I redownloaded the project and I'm having the same issue and error messages. 
When running `pod install` I get `Pod installation complete` and `Using SceneKitVideoRecorder (1.3.1)`.

**Comment by mariedm** [comment]
Since I can't run the project I can't remove the demo app from my device. So I guess I have a clean install ;)

**Comment by okaris** [comment]
After pod install in the demo project directory, are you still getting "diff: /Podfile.lock: No such file or directory and The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation"?

Otherwise I have added a new status handler and it should print the error on startWriting().

Since I can't reproduce this issue I am counting on your input.

**Comment by mariedm** [comment]
Yes I still have these errors:
- `diff: /Podfile.lock: No such file or directory`
- `diff: /Manifest.lock: No such file or directory`
- `error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.`

And these warning that might help you:
- `Target integrity: The file “Pods-SceneKitVideoRecorderDemo.debug.xcconfig” couldn’t be opened because there is no such file.`
- `Target integrity: The file “Pods-SceneKitVideoRecorderDemo.release.xcconfig” couldn’t be opened because there is no such file.`
- `Dependency Analysis Warning: The file “Pods-SceneKitVideoRecorderDemo.debug.xcconfig” couldn’t be opened because there is no such file.`

Could it be a path issue..?

**Comment by okaris** [comment]
I have downloaded the repo to a different dir and its running normally. Its basic but are you running pod install in the Demo directory?

**Comment by mariedm** [comment]
Yes I did. 
Anyway if I try in the parent directory I get `[!] No 'Podfile' found in the project directory.`.

**Comment by mariedm** [comment]
I can download it again and move it elsewhere if you'd like?

**Comment by mariedm** [comment]
I removed the pod from my test project (the one reproducing your demo project) and imported the classes manually (I just re-downloaded the zip file).

I have the same issue described in my first message: I call `startWriting` then `stopWriting`. Nothing happens. Then I recall `startWriting` and I get `*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriter startWriting] Cannot call method when status is 1'` (since the recording has not been properly stoped, it's actually still writing). 
One difference with my first message though: status is 1 (writing) and not 3 (failed).

**Comment by okaris** [comment]
I suspect it is a leftover output file. I have changed the file handling a bit. Can you try again please?

**Comment by okaris** [comment]
Closing because I can’t reproduce this anymore.

**Comment by eric-krikey** [comment]
I am having the issue of `[AVAssetWriterInput markAsFinished] Cannot call method when status is 0'`

I am on version 1.3.8. I did have to adjust a few things for swift 4 compatibility, but that seemed fairly trivial. This only happens when using audio as well. If I comment out `recorder?.setupMicrophone()` it works just fine. But obviously I want to have audio, so that isn't a real fix.

**Comment by okaris** [comment]
Can you please try with the new version (1.4.0)

**Comment by eric-krikey** [comment]
I have done it with version 1.4.1 and the audio is working! The only problem is that it is very quiet, even with my audio turned all the way up. So I don't know if that is something that I need to adjust on my end in the configuration, but thank you so much for the fix!!
